#!/usr/bin/env groovy

def generateStage(serv) {
    return {
        stage("${serv}"){
            if("${serv}.contains("build")){
                echo "in"
            }
            else{
                echo "out"
            }
        }
    }
}

def list
def tagname
def tagnumber

pipeline {
    agent any
    stages {
        stage('parallel stage') {
            steps {
                script {
                    def job = ["dir1 build", "dir1 docker push", "dir2 build", "dir2 docker push"]
                    def parallelStagesMap = job.collectEntries {
                        ["${it}" : generateStage(it)]
                    }
                    parallel parallelStagesMap
                }
            }
        }
    }
}
